baseURL = 'LoRose2.github.io'
languageCode = 'en-us'
title = 'Logan Rosentreter'
contentDir = 'content'
enableEmoji = true

[module]
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

[markup]
    [markup.tableOfContents]
      endLevel = 3
      startLevel = 1
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # https://jdhao.github.io/2019/12/29/hugo_html_not_shown/
  [markup.goldmark.parser]
    [markup.goldmark.parser.attribute]
      block = true

# [[menu.primary]]
#     name  = "Docs"
#     url = "/docs/"
#     identifier = "docs"
#     weight = 10
    
[params.docs] 
  alwaysopen = true
  darkMode = true
  themeColor = "cardinal"